import type { Project, Message } from './types';

export const projects: Project[] = [
  {
    id: '1',
    title: 'E-commerce Platform',
    description: 'A full-featured e-commerce platform with a custom CMS, payment integration, and a modern, responsive user interface.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'online store',
    tags: ['Next.js', 'TypeScript', 'Stripe', 'PostgreSQL'],
    liveUrl: '#',
    githubUrl: '#',
    order: 1,
  },
  {
    id: '2',
    title: 'Project Management Tool',
    description: 'A collaborative project management tool with features like task tracking, team chat, and file sharing, built with a real-time backend.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'dashboard chart',
    tags: ['React', 'Node.js', 'WebSocket', 'MongoDB'],
    liveUrl: '#',
    githubUrl: '#',
    order: 2,
  },
  {
    id: '3',
    title: 'Personal Blog CMS',
    description: 'A lightweight and fast blog CMS with a markdown editor, static site generation for performance, and a clean, minimalist design.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'writing minimalist',
    tags: ['Next.js', 'Tailwind CSS', 'Markdown'],
    liveUrl: '#',
    githubUrl: '#',
    order: 3,
  },
  {
    id: '4',
    title: 'Data Visualization Dashboard',
    description: 'An interactive dashboard for visualizing complex datasets, featuring various chart types and data filtering capabilities.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'analytics graph',
    tags: ['D3.js', 'React', 'API Integration'],
    liveUrl: '#',
    githubUrl: '#',
    order: 4,
  },
  {
    id: '5',
    title: 'Fitness Tracking App',
    description: 'A mobile-friendly web app to track workouts, set fitness goals, and monitor progress over time.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'mobile application',
    tags: ['PWA', 'React', 'Firebase'],
    liveUrl: '#',
    githubUrl: '#',
    order: 5,
  },
];

export const messages: Message[] = [
  {
    id: '1',
    name: 'Jane Doe',
    email: 'jane.doe@example.com',
    message: 'Interested in collaborating on a new project. Your work looks impressive!',
    createdAt: new Date('2023-10-26T10:00:00Z'),
    read: false,
  },
  {
    id: '2',
    name: 'John Smith',
    email: 'john.smith@example.com',
    message: 'Had a question about your project management tool. Could you provide more details?',
    createdAt: new Date('2023-10-25T14:30:00Z'),
    read: true,
  },
  {
    id: '3',
    name: 'Emily White',
    email: 'emily.white@example.com',
    message: 'Just wanted to say I love your portfolio design! Very clean and professional.',
    createdAt: new Date('2023-10-24T09:15:00Z'),
    read: true,
  },
];
